version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: calendar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: calendar_user
      POSTGRES_PASSWORD: calendar_pass
      POSTGRES_DB: calendar_db
    ports:
      - "5432:5432"
    volumes:
      - calendar_pgdata:/var/lib/postgresql/data

volumes:
  calendar_pgdata:
